dist: xenial
language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DJANGO=2.2 DB=postgres
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database flight_db_3;' -U postgres
script:
  - python manage.py test
after_success:
  coveralls