# Generated by Django 2.2.1 on 2019-06-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='name',
            new_name='flight_name',
        ),
    ]
