# Generated by Django 2.2.1 on 2019-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApi', '0003_auto_20190602_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first class', 'First Class')], max_length=20),
        ),
    ]
