# Generated by Django 2.2.1 on 2019-06-04 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApi', '0004_auto_20190602_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='no_of_passenger',
        ),
        migrations.AlterField(
            model_name='flight',
            name='passenger',
            field=models.ForeignKey(on_delete='cascade', related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
